sudo: false
dist: trusty
language: scala
scala:
  - 2.11.8
before_install:
  - python -V
  - pip -V
script:
  - jdk_switcher use openjdk8
  - sbt spDist
  # Install a version of Spark to test this against
  - wget http://d3kbcqa49mib13.cloudfront.net/spark-2.0.2-bin-hadoop2.7.tgz
  - tar xf spark-2.0.2-bin-hadoop2.7.tgz
  # TODO make this less fragile.
  - export PACKAGE=file://`pwd`/target/spark-jython-udf-0.0.1.zip
  - spark-2.0.2-bin-hadoop2.7/bin/spark-submit --jars $PACKAGE --py-files=$PACKAGE examples/jython_udf_perf.py
  
# Cache these at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
